name: Full Deploy & Log Output

on:
  push:

jobs:
  full-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up SSH key and known hosts
        run: |
          mkdir -p ~/.ssh
          cat << 'EOF' > ~/.ssh/id_rsa
          # (Insert your private key here)
          -----BEGIN RSA PRIVATE KEY-----
          ...
          -----END RSA PRIVATE KEY-----
          EOF
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 13.48.234.161 >> ~/.ssh/known_hosts || (sleep 5 && ssh-keyscan -H 13.48.234.161 >> ~/.ssh/known_hosts)

      - name: Manual Deploy Script with Live Logging
        run: |
          set -xe
          ssh -o StrictHostKeyChecking=no ubuntu@13.48.234.161 <<'EOF'
            sudo apt update | tee ~/apt-update.log
            sudo apt install -y nodejs npm git | tee ~/apt-install.log
            node -v && npm -v | tee ~/node-npm-version.log

            git clone https://github.com/AnuragChougule/DevOps.git | tee ~/git-clone.log
            cd DevOps/backend

            rm -rf node_modules | tee ~/rm-node_modules.log
            rm -f package-lock.json | tee ~/rm-package-lock.log
            npm install | tee ~/npm-install.log

            nohup npm start > ~/npm-start.log 2>&1 &
            sleep 10
            tail -n 20 ~/npm-start.log

            sudo npm install -g ganache-cli | tee ~/ganache-cli-install.log
            nohup ganache-cli -p 7545 > ~/ganache.log 2>&1 &
            sleep 5
            tail -n 20 ~/ganache.log

            sudo apt install -y nginx | tee ~/nginx-install.log
            sudo systemctl restart nginx
            sudo cp -r ~/DevOps/frontend/* /var/www/html/
            sudo systemctl restart nginx

            sudo systemctl status nginx | tee ~/nginx-status.log
            sudo tail -n 20 /var/log/nginx/error.log || true

            echo "--- Node/NPM Version ---"
            cat ~/node-npm-version.log
            echo "--- Backend Start Log ---"
            tail -n 20 ~/npm-start.log
            echo "--- Ganache Log ---"
            tail -n 20 ~/ganache.log
            echo "--- Nginx Status ---"
            tail -n 10 ~/nginx-status.log
          EOF
